language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

after_script:
  phpunit --coverage-clover build/logs/clover.xml
  - CODECLIMATE_REPO_TOKEN=b1e653a6b0fd9365df44fb062ac5cf5afe63c84fecd37e4dc97fbef00febf553 ./vendor/bin/test-reporter

script: phpunit